version: 2
registries:
  rubygems-server-enterprise-contribsys-com:
    type: rubygems-server
    url: https://enterprise.contribsys.com/
    username: "${{secrets.RUBYGEMS_SERVER_ENTERPRISE_CONTRIBSYS_COM_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_ENTERPRISE_CONTRIBSYS_COM_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
    timezone: US/Eastern
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: rake
    versions:
    - 13.0.3
  registries:
  - rubygems-server-enterprise-contribsys-com
